packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@neondatabase/serverless": 1.1.0
  "@types/node": ^26.0.0
  drizzle-kit: 0.31.10
  drizzle-orm: 0.45.2
  nanoid: 6.0.0
  playwright-core: 1.61.1
  typescript: ^5
  zod: 4.4.3

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@0.2.4"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

allowBuilds:
  esbuild: true
